/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_houshuai_opencvdemo_PicFaceRecoder */

#ifndef _Included_com_example_houshuai_opencvdemo_PicFaceRecoder
#define _Included_com_example_houshuai_opencvdemo_PicFaceRecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_houshuai_opencvdemo_PicFaceRecoder
 * Method:    getFaceNumber
 * Signature: ([ILjava/lang/String;)I
 */
JNIEXPORT jintArray  JNICALL Java_com_example_houshuai_opencvdemo_PicFaceRecoder_getFaceNumber
  (JNIEnv *, jclass, jintArray, jstring,jint ,jint);

#ifdef __cplusplus
}
#endif
#endif
